[package]
name = "xjbutil"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unchecked_unwrap = "3"

async-std = { optional = true, version = "1" }
futures = { optional = true, version = "0.3" }
pollster = { optional = true, version = "0.2" }
tokio = { optional = true, version = "1", features = ["rt", "sync", "time"] }

[features]
default = ["enable-all", "async-tokio"]
enable-all = ["async", "defer", "either", "fat_ptr", "korobka", "makro", "mem", "std-ext", "unchecked", "void", "zvec"]

async = ["futures"]
async-astd = ["async-std"]
async-pollster = ["pollster"]
async-tokio = ["tokio"]
defer = []
either = []
fat_ptr = []
korobka = []
makro = []
mem = []
std-ext = []
unchecked = []
void = []
zvec = []
