name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rust nightly
      run: rustup install nightly
    - name: Install miri
      run: rustup component add miri --toolchain nightly
    - name: Install xargo
      run: cargo +nightly install xargo
    - name: Run tests
      run: make test_all_no_miri_async
